version: '3'
services:
  # postgres:
  #   image: postgres:latest
  #   container_name: rangoon-postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - rangoonPostgresDB:/var/lib/postgresql/data
  #   env_file:
  #     - ./.env


  redis:
    image: redis:latest
    container_name: rangoon-redis
    ports:
      - '6379:6379'
    volumes:
      - rangoonRedisDB:/data


volumes:
  # rangoonPostgresDB:
  rangoonRedisDB:
