name: Build

on:
  push:
    branches:
      - main
      - github-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Build client
    #   working-directory: client
    #   run: |
    #     cd ./client
    #     pnpm install
    #     pnpm run build

    - name: Build server
      working-directory: server
      run: |
        cd ./server
        pnpm install
        pnpm run build

