name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ip >> ~/.ssh/known_hosts

      - name: Deploy to Remote Server
        run: |
          ssh ${{ secrets.SSH_SERVER }} 'bash -s' < deploy.sh
