# Add this to your .github/workflows/main.yml file

name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass


      - name: Deploy to SSH server
        env:
          SSH_SERVER: ${{ secrets.SSH_SERVER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          chmod +x ./deploy.sh
          sshpass -p '$SSH_PASSWORD' ssh "$SSH_SERVER" 'bash -s' < ./deploy.sh
