name: Deploy to Server

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout@v2

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 192.168.100.253 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh rangoondiscount@192.168.100.253 'bash -s' < deploy.sh
